apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.name" . }}-config
data:
  POSTGRES_PORT: {{ .Values.postgres.port | quote}}
  POSTGRES_HOST: {{ .Values.postgres.host }}
  DEMO_CATALOG_LOCATION: {{ .Values.catalog.demoCatalogLocation }}
  CUSTOM_CATALOG_LOCATION: {{ .Values.catalog.customCatalogLocation }}
  BASE_URL: {{ .Values.backstage.baseURL }}

