apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc}}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc}}
  GITHUB_TOKEN: {{ .Values.github.accessToken | b64enc}}
